on:
  workflow_call:
    inputs:
      subject:
        required: true
        type: string
      message:
          required: true
          type: string
          
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: XAPP - ${{ inputs.subject }}
        # Required recipients' addresses:
        to: ${{ github.event.inputs.userEmail }}
        # Required sender full name (address can be skipped):
        from: Xapp # <Xapp@app.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: ${{ inputs.message }}
